name: Build Docker Image

on:
  push:
    branches:
      - main  # Workflow ini akan berjalan setiap kali ada perubahan di cabang 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Menentukan agar build dijalankan di lingkungan Ubuntu

    steps:
      # Langkah pertama: Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v2  # Ini mengunduh kode sumber repository

      # Langkah kedua: Set up Docker Buildx untuk kemampuan build multi-platform
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Langkah ketiga: Login ke Docker Hub menggunakan username dan password yang disimpan di GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Ambil username dari GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Ambil password dari GitHub Secrets

      # Langkah keempat: Build Docker image dan push ke Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t yourusername/yourrepository .  # Membangun Docker image
          docker push yourusername/yourrepository  # Mendorong Docker image ke Docker Hub
